version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
    volumes:
      - /usr/src/app/node_modules
    restart: always

networks:
  default:
    driver: bridge
